services:
  db:
    image: mariadb:10.6.4-focal
    container_name: mysql-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    networks:
      - app_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer-db-ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:
  wordpress_data:

networks:
  app_network:

